### ISSUE TITLE
Cannot display Chinese correctly

### ISSUE THREAD

**Issue by yueduz** [OpenMarshal/npm-WebDAV-Server#11] opened 2017-07-28 14:43 UTC
![2017-07-28 22-42-59](https://user-images.githubusercontent.com/1448159/28722383-2f6f5cde-7379-11e7-8b2f-ef2ef5722394.png)

**Comment by AdrienCastex** [comment] 2017-07-30 15:05
Hello,

It is working pretty well on :
* [Windows embedded client](https://user-images.githubusercontent.com/6717491/28754505-d80f7f44-7546-11e7-9b29-53dba6a051eb.png)
* [BitKinex](https://user-images.githubusercontent.com/6717491/28754507-e623a074-7546-11e7-91a7-ba53627e2a24.png)
* [Ubuntu GUI](https://user-images.githubusercontent.com/6717491/28754618-f2d22d34-7548-11e7-8719-d7ea2075c8c5.png)
* davfs
* cadaver

What WebDAV client are you using?

**Comment by yueduz** [comment] 2017-07-31 04:33
![2017-07-31 12-33-01](https://user-images.githubusercontent.com/1448159/28762875-7f69ab1a-757f-11e7-8f6b-c65f0a6a2d32.png)

**Comment by AdrienCastex** [comment] 2017-07-31 09:30
In a terminal, what `echo $LANG` displays to you?

**Comment by yueduz** [comment] 2017-07-31 11:15
```
lei@leiPC:/home/lei> echo $LANG                                  17-07-31 19:15
zh_CN.UTF-8
lei@leiPC:/home/lei>  
```

**Comment by yueduz** [comment] 2017-07-31 12:24
I think the decodeURI is needed

**Comment by yueduz** [comment] 2017-07-31 13:09
![2017-07-31 21-07-16](https://user-images.githubusercontent.com/1448159/28779038-5214012c-75c7-11e7-80d6-46e7e0bdd07d.png)

The path can display Chinese
![2017-07-31 21-08-54](https://user-images.githubusercontent.com/1448159/28779091-883e7fac-75c7-11e7-85d8-d53f45f78fb7.png)
？？？

**Comment by AdrienCastex** [comment] 2017-07-31 15:19
I can't reproduce the error, so it's like trying to fix a problem while being blind.

I removed some encodings. Please try the version `2.0.17`.

**Comment by yueduz** [comment] 2017-07-31 16:06
Thanks. Now I can display the Chinese documents and catalogues properly. But with the new problem, you can't create folders in a secondary folder, only files can be created.
![2017-08-01 00-05-39](https://user-images.githubusercontent.com/1448159/28786876-3a08ea66-75e0-11e7-9aec-150a2275b31d.png)

![2017-08-01 00-04-19](https://user-images.githubusercontent.com/1448159/28786828-07748646-75e0-11e7-9acd-6aac9d291656.png)

**Comment by AdrienCastex** [comment] 2017-07-31 16:21
I am glad that solved the first problem.

The problem about the creation of a sub folder is a problem of the version `2.0.17`.
Do you still have this problem after updating to the version `2.0.18`?

**Comment by yueduz** [comment] 2017-07-31 23:01
Yes, there are

Adrien Castex <notifications@github.com>于2017年8月1日周二 上午12:21写道：

**Comment by AdrienCastex** [comment] 2017-08-01 07:46
The `Conflict` response status makes me think that you tried to create a folder called `test` while there is already a file with this name.

**Comment by yueduz** [comment] 2017-08-01 10:52
Watch this video
[Screencast from 08-01-2017 06:50:30 PM.zip](https://github.com/OpenMarshal/npm-WebDAV-Server/files/1190319/Screencast.from.08-01-2017.06.50.30.PM.zip)

**Comment by AdrienCastex** [comment] 2017-08-01 13:45
Thanks to your video, I've been able to reproduce the error.

I found that the problem came from using a relative path instead of an absolute path in the `MKCOL` method, which leaded the server to look for the resource `/aa` instead of `/physicalFolder/aa`.

I published the fix (`v2.0.19`). I let you close the issue if you think that the problem is gone.

Thank you very much for your contribution.

**Comment by yueduz** [comment] 2017-11-03 06:28
I have been updated to the new version
![2017-11-03 14-28-35](https://user-images.githubusercontent.com/1448159/32362324-57ae6244-c036-11e7-81e3-c3a826bc3156.png)

**Comment by AdrienCastex** [comment] 2017-11-04 09:30
Hello,

I was encoding the content of the `href` tag and the `displayname` tag. I removed the encoding of the `displayname` to display the name of the file with all special characters without the need to decode it (`v2.3.9`). Most WebDAV clients are decoding the `displayname`, but not all.

I was able to reproduce the problem on Nautilus and I fixed the issue.
I let you close the issue if you think that the issue is fixed for you too.

Thank you very much for your contribution.

**Closed** 2017-11-05 11:55 UTC
