### ISSUE TITLE
Microsoft Excel not able to save back changes

### ISSUE THREAD

**Issue by fabrodz** [OpenMarshal/npm-WebDAV-Server#81] opened 2020-05-25 16:37 UTC
In Excel I get the error message below:

![jcW30](https://user-images.githubusercontent.com/25328542/82830335-d0dcde80-9e8b-11ea-9546-b988cdf6d8e4.png)

Obviusly i've checked the document is not opened by anyone else, (it's my develoment enviroment) and if I hit the "keep my version" button, the document is saved correctly.

However Word and PowerPoint work OK. I doesn't have any trouble saving back changes.

Has it already happened to someone? Any clue to test?

**Comment by gustter** [comment] 2020-05-26 15:42
+1

**Comment by btimby** [comment] 2020-05-29 22:46
I found that removing the `Dav: 1,2` header resolves this. My code:

```javascript
const MS_WEBDAV = RegExp('^Microsoft');

...

function setHeaders(arg, next) {
  // This header, if present causes problems for Office 365. When present, Office 365
  // treats the server as a SharePoint server, and makes calls to /_api/... to support
  // collaboration. These fail and thus files cannot be saved.
  const userAgent = arg.request.headers['user-agent'];
  if (userAgent && MS_WEBDAV.test(userAgent)) {
    arg.response.removeHeader('dav');
  }
  next();
}

...

    this.server.beforeRequest(setHeaders);
```

**Comment by btimby** [comment] 2020-05-29 22:48
Caution, removing this header breaks Nautilus. That is why I selectively remove it only for Microsoft clients. As my comment states, when this header is present, you will see requests to the root of the server for /_api... URLs. Googling indicates this URL is used by Sharepoint. So Excel 365 is getting confused when it detects the server type.

I will note that this fixed the problem, but not completely. Deploying this change to my development stack and beta stack worked. However, in production this problem persists. I am still trying to track down what is different between production and the other environments. Most likely another header or something that is not present or present...

**Comment by fabrodz** [comment] 2020-05-30 01:18
@btimby I've tested your code and double checked that `dav: 1,2` is not returned by the server, but still having the same problem, maybe have another change in your fork?

**Comment by btimby** [comment] 2020-05-30 01:35
Well, like I said it worked in my test environments but not production. There is something else I am missing. I am actively investigating. I will share what I find here.

I don't actually use a fork but I have implemented all of the available interfaces.

**Comment by btimby** [comment] 2020-05-30 01:38
I was convinced I had it fixed by removing the `Dav` header until it went to production today.

**Comment by fabrodz** [comment] 2020-05-30 02:19
Well if it works in your dev environment, then probably something you've missed. I'll keep my research but if you got any progress please share it here.

**Comment by fabrodz** [comment] 2020-06-02 01:20
Finally, I found it! This error is caused because Excel requests the file a second time if the user selects "Enable Editing". 
If the Server sends the file again (with code 200) instead of returning a 304 (Not Modified) Office seems to believe that somebody has changed the document even if this is not the case.
In my case, have a custom implementation of the FileSystem, so I'm using the `ETag` header, (generated with [etag ](https://www.npmjs.com/package/etag)npm module, from the file metadata "last update" value) and checking the `If-None-Match` header in future requests to manage this issue.
I hope it helps.

**Comment by btimby** [comment] 2020-06-02 02:57
That makes sense. How do you do etags in webdav server? Any code or doc links that might help? I also have a custom fs.  I will try in the morning.

**Comment by fabrodz** [comment] 2020-06-02 14:33
In my custom fs within the `_openReadStream` function:

```
let etagString = etag(new Date(fileMetaData.timeStamp).toUTCString());
if (req.headers['if-none-match'] == etagString) res.status(304).send();
```

In my implementation the `fileMetaData.timeStamp` returns the last update timestamp, but you can generate the etag from the whole file.

Important note:
Once you return the `ETag `header, all the subsequent requests will come with the `if-none-match` header.

**Comment by btimby** [comment] 2020-06-02 15:20
How are you adding the etag header? I implemented the `_etag` method of the `FileSystem` class but the etag header is not being emitted.

Perhaps because of this I am not seeing the second GET request when I click "enable editing" instead I see a `POST` to `/_api/web/GetFileByUrl(@v)/ListItemAllFields/GetSharingInformation` After which I receive the error from excel about other user modifications.

**Comment by btimby** [comment] 2020-06-02 16:39
@fabrodz I can confirm this works. I am using the built in webserver (as opposed to express). I assume you are using express (or something else) as your header and response handling differs. Here is my solution:

```javascript
  _openReadStream(pathObj, ctx, callback) {
    const path = normPath(pathObj);
    logger.debug(`_openReadStream(${path})`);

    // Stat the path so we can check the etag.
    ctx.context.user.fs.stat(path, (e, json) => {
      if (e) {
        if (e.statusCode === 404) {
          callback(webdav.Errors.ResourceNotFound);
        } else {
          logger.error(e);
          callback(e);
        }

        return;
      }

      const etagValue = etag(new Date(json.time).toUTCString());
      if (ctx.context.request.headers['if-none-match'] === etagValue) {
        logger.debug('Returning 304 as file has not changed.');
        ctx.context.response.statusCode = 304
        ctx.context.response.end();
        return;
      }

      try {
        ctx.context.user.fs.createReadStream(path, (createError, stream) => {
          if (createError) {
            logger.error(createError);
          }
  
          ctx.context.response.setHeader('etag', etagValue);
          callback(createError, stream);
        });
      } catch (e) {
        logger.error(e);
        callback(e);
      }
    });
  }
```

Like you I am using the npm `etag` module. The important bit is that when opening a stream for reading, check the `'if-none-match'` header against the file's etag (derived from last modified). If they don't match (or header is not present) open the stream and set the etag header. If they _do_ match, then return a 304 immediately without opening the stream.

NOTE: The `ctx.context.fs...` stuff is the API for the filesystem I am exposing...

Good find sir!!!

@AdrienCastex I think this solution could be integrated into the library if you are interested.

**Comment by Papooch** [comment] 2020-11-03 16:55
I know this may be out topic, but it seems that you guys have managed to even open an office document through the webdav server. Would you please look at my issue over here https://github.com/OpenMarshal/npm-WebDAV-Server/issues/90 ? Thanks a ton.

**Comment by clehmeier** [comment] 2021-06-01 10:26
Hello,

I am facing same issue using Excel 2019. Using Word is working without problems. 

for a fast workaround unchecking protected view of documents from internet and unsafe locations in Excel Trust Center solves the problem:
![2021-06-01 12_16_09-Trust Center](https://user-images.githubusercontent.com/70153794/120307423-436c6f80-c2d3-11eb-8a09-4d70ac49b05b.png)

But this is really unsafe for production environment.

I tried a lot and can not find any solution.
So, could anybody help with a solution using express and local storage? 

@btimby, @fabrodz:
Could your etag-solution be used for express and local storage? 

thanks a lot!
  Christian

**Comment by fabrodz** [comment] 2021-06-07 16:00
> Finally, I found it! This error is caused because Excel requests the file a second time if the user selects "Enable Editing".
> If the Server sends the file again (with code 200) instead of returning a 304 (Not Modified) Office seems to believe that somebody has changed the document even if this is not the case.
> In my case, have a custom implementation of the FileSystem, so I'm using the `ETag` header, (generated with [etag ](https://www.npmjs.com/package/etag)npm module, from the file metadata "last update" value) and checking the `If-None-Match` header in future requests to manage this issue.
> I hope it helps.

Check this solution, I'm using express and it worked for me. AFAIK there is no "official" implementation to solve this issue.

**Comment by clehmeier** [comment] 2021-06-09 06:43
@fabrodz: thank's for your reply.

finally I switched to custom filesystem and took [https://github.com/OpenMarshal/npm-WebDAV-Server-Types/tree/master/repositories/virtual-stored](https://github.com/OpenMarshal/npm-WebDAV-Server-Types/tree/master/repositories/virtual-stored) as base.

works fine, but keeping problem of _**Excel not able to save back changes**_.

Then I tried to follow @btimby's code for `_openReadStream(pathObj, ctx, callback)` (2nd July 2020), but whatever I try, ctx.context.request.headers['if-none-match'] is _undefined_ to any time.

this is my code for _openReadStream of class `VirutalStoredFileSystem extends webdav.FileSystem`:
```
protected _openReadStream?(path: webdav.Path, ctx: webdav.OpenReadStreamInfo, callback: webdav.ReturnCallback<Readable>): void {
        
        // Dumping out the headers
        console.log(ctx.context['request'].headers);
        
        const r = this.resources[path.toString()];
        if (!r)
            return callback(webdav.Errors.ResourceNotFound);

        callback(null, this.allocator.readStream(r.filename))
}
```

These are the dumped headers for first open excel file in read only mode and 2nd time for editing mode (both exact same):
```
{
  connection: 'Keep-Alive',
  'content-type': 'text/xml; charset="utf-8"',
  authorization: 'Bearer',
  'user-agent': 'Microsoft Office Excel 2014',
  'x-office-major-version': '16',
  'x-ms-cookieuri-requested': 't',
  'x-featureversion': '1',
  'accept-auth': 'badger,Wlid1.1,Bearer',
  depth: '0',
  translate: 'f',
  'x-idcrl_accepted': 't',
  host: '127.0.0.1:1901'
}
```

I hope somebody could help me what I am doing wrong.

Thanks!
  Christian

**Comment by fabrodz** [comment] 2021-06-09 16:05
This is my js code, I hope it helps:

```
CustomFS.prototype._openReadStream = async function (path, info, callback) {
        let req = info.context.request;
        let res = info.context.response;
        let id = req.path.split('/')[3];
        try {
            let stream = await FileFS.readStream(id, null, req.ctx); //Custom implementation to retrieve the file
            let etagString = etag(new Date(stream.fileMetaData.timeStamp).toUTCString());
            if (req.headers['if-none-match'] == etagString) res.status(304).send(); //This line do the trick
            let m = mime.lookup(stream.fileMetaData.ext);
            res.setHeader('Content-type', m);
            let cd = contentDisposition(stream.fileMetaData.fileName);
            res.setHeader('Content-disposition', cd);
            res.setHeader('ETag', etagString);
            stream.on ('error', () => {
                res.status(500).send();
            });
            callback(null, stream);
        } catch (err) {
            res.status(500).send();
        }
    };
```

As you may see, the applications sends 304 in case of matching etags, this happens on the second requests that asks for editing mode. Obiusly this code works for my custom needs, but i think it's a good example and the concept behind the solution is pretty clear.

**Comment by clehmeier** [comment] 2021-06-10 11:28
Hi fabrodz,

thank you so much for your support! 

**Code is running and Excel can save after switch to edit mode properly.**

I did not realize that the request header **if-none-match** is created by the Etag and missed to add ctx.context.response.setHeader('etag', etagValue) before callback.

so, thanks to @btimby and many thanks for your patience @fabrodz!

Christian

**Closed as completed** 2021-06-10 12:33 UTC

**Comment by periyasamy2git** [comment] 2024-04-01 06:55
> @fabrodz I can confirm this works. I am using the built in webserver (as opposed to express). I assume you are using express (or something else) as your header and response handling differs. Here is my solution:
> 
> ```js
>   _openReadStream(pathObj, ctx, callback) {
>     const path = normPath(pathObj);
>     logger.debug(`_openReadStream(${path})`);
> 
>     // Stat the path so we can check the etag.
>     ctx.context.user.fs.stat(path, (e, json) => {
>       if (e) {
>         if (e.statusCode === 404) {
>           callback(webdav.Errors.ResourceNotFound);
>         } else {
>           logger.error(e);
>           callback(e);
>         }
> 
>         return;
>       }
> 
>       const etagValue = etag(new Date(json.time).toUTCString());
>       if (ctx.context.request.headers['if-none-match'] === etagValue) {
>         logger.debug('Returning 304 as file has not changed.');
>         ctx.context.response.statusCode = 304
>         ctx.context.response.end();
>         return;
>       }
> 
>       try {
>         ctx.context.user.fs.createReadStream(path, (createError, stream) => {
>           if (createError) {
>             logger.error(createError);
>           }
>   
>           ctx.context.response.setHeader('etag', etagValue);
>           callback(createError, stream);
>         });
>       } catch (e) {
>         logger.error(e);
>         callback(e);
>       }
>     });
>   }
> ```
> 
> Like you I am using the npm `etag` module. The important bit is that when opening a stream for reading, check the `'if-none-match'` header against the file's etag (derived from last modified). If they don't match (or header is not present) open the stream and set the etag header. If they _do_ match, then return a 304 immediately without opening the stream.
> 
> NOTE: The `ctx.context.fs...` stuff is the API for the filesystem I am exposing...
> 
> Good find sir!!!
> 
> @AdrienCastex I think this solution could be integrated into the library if you are interested.

**I'm also using nodejs webdav-server in which file I have add this line ??. If I'm adding this to main file i'm getting error**

**Comment by btimby** [comment] 2024-04-01 16:16
@periyasamy2git At a high-level, you first need to include `etag` headers in your responses. This will cause the client (Excel) to send `if-none-match` headers with requests. Once this is happening, you can check the value of the given `if-none-match` when opening a stream and return a 304 when they do match. If they don't match, you open the stream as usual.

Your solution will be custom to your situation, but the above is what worked for me.

**Comment by btimby** [comment] 2024-04-01 16:17
@periyasamy2git Basically excel is making a second request and expects a 304 to indicate the file has not been modified since it's first request. Returning anything except a 304 indicates that the file has been modified and Excel fails to open the file for editing.
