### ISSUE TITLE
Move tasks 'moves' files but copies directories

### ISSUE THREAD

**Issue by ChristophAtAdlos** [OpenMarshal/npm-WebDAV-Server#19] opened 2017-09-28 10:06 UTC
If I move a file, all is well. But if I move a directory, the source directory will not be removed. This behavior is copy task like and not a real move.

See the header information:
```
[WebDAV] >> MOVE http://localhost:8080/webdav/test/ Headers: RequestContextHeaders {
headers: 
   { host: 'localhost:8080',
     connection: 'keep-alive',
     origin: 'http://localhost:8080',
     overwrite: 'F',
     destination: 'http://localhost:8080/webdav/moved/test/',
     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
     accept: '*/*',
     referer: 'http://localhost:8080/ObjectBrowser/index.html',
     'accept-encoding': 'gzip, deflate, br',
     'accept-language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4',
     cookie: 'io=o8P-qU_s0PHh5NcZAAAC' },
  isSource: false,
  host: 'localhost:8080',
  depth: undefined,
  contentLength: 0 }  |  { host: 'localhost:8080',
  connection: 'keep-alive',
  origin: 'http://localhost:8080',
  overwrite: 'F',
  destination: 'http://localhost:8080/webdav/moved/test/',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36',
  accept: '*/*',
  referer: 'http://localhost:8080/ObjectBrowser/index.html',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4',
  cookie: 'io=o8P-qU_s0PHh5NcZAAAC' } > 204 No Content
```

After this move, the directory `test` can be found at `/webdav/test/` (original) and also at `/webdav/moved/test/` (the copy that shuld be a moved directory).

Versions:
webdav-server: 2.3.3
node:  LTS 6.11.3
os. Windows 10 Pro x64

**Comment by ChristophAtAdlos** [comment] 2017-09-28 15:23
Now it works how it should. I can't get out what was the problem...

**Comment by AdrienCastex** [comment] 2017-10-01 11:56
Hello,

I tested a lot of possibilities and I can't reproduce this error.

I have two questions :
* Were you using a `VirtualFileSystem`, a `PhysicalFileSystem`, a custom file system?
* Was it a cross-file-system move? (Move from one file system to another)

I will update the way to generate the `eTag` on the directories to be more reliable. A WebDAV client can use the `eTag` to know if the content of a resource changed and use the live version instead of the cached one, but maybe some clients use it for directories too.

**Comment by lastuniverse** [comment] 2018-01-18 20:03
I have this problem too
my server code
```
const users = {
"belikov": 		{ "userdir":"Беликов", "login":"belikov", "pass":"111" },
"surmanidze": 	{ "userdir":"Сурманидзе", "login":"surmanidze", "pass":"111"}
};

const webdav = require('webdav-server').v2;

// User manager (tells who are the users)
const userManager = new webdav.SimpleUserManager();

// Privilege manager (tells which users can access which files/folders)
const privilegeManager = new webdav.SimplePathPrivilegeManager();

for(let i in users){
	let u = users[i];
	const user = userManager.addUser(u.login, u.pass, false);

	privilegeManager.setRights(user, '/', [  
		'canRead',
		'canReadLocks',
		'canReadContent',
		'canReadContentTranslated',
		'canReadContentSource',
		'canReadProperties'
	]);
	privilegeManager.setRights(user, '/Пользователи/'+u.userdir+'', [ 'all' ]);
}

const server = new webdav.WebDAVServer({
    // HTTP Digest authentication with the realm 'Default realm'
    httpAuthentication: new webdav.HTTPDigestAuthentication(userManager, 'Default realm'),
    privilegeManager: privilegeManager,
    port: 1901
});

server.afterRequest((arg, next) => {
    console.log('>>', arg.request.method, arg.uri, '>', arg.response.statusCode, arg.response.statusMessage);
    next();
})

server.setFileSystem('/', new webdav.PhysicalFileSystem('/home/mcserv/work/rima/public/share'), (success) => {
    server.start(() => console.log('READY'));
})
```
[demo in windows 7 (video)](/www.youtube.com/watch?v=_yvGx3Rmb1c&feature=youtu.be)

in linux npm-webdav-server console:
```
...

>> PROPFIND undefined > 404 Not Found
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 404 Not Found
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 207 Multi-Status
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 404 Not Found
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 207 Multi-Status
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 404 Not Found
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 207 Multi-Status
>> PROPFIND undefined > 401 Unauthorized
>> PROPFIND undefined > 404 Not Found
...
```


`wdfs -u surmanidze -p 111 http://192.168.0.151:1901/ ./temp`
[demo in linux console (video)](https://www.youtube.com/watch?v=9F0L2Llv_kc&feature=youtu.be)

**Comment by AdrienCastex** [comment] 2018-01-22 08:10
Hello,

The problem you were encountering was when executing a `PROPPATCH` ; the privilege check was done after the resource-locked check, so it was returning a `423 Locked` (because the resource is locked in the process by the WebDAV client) instead of a `401 Unauthorized`. It is now fixed in the version `2.3.14`.

I fixed the [wiki](https://github.com/OpenMarshal/npm-WebDAV-Server/wiki/Quick-Start-Guide-%5Bv2%5D) when I saw that your logs have `undefined` values.
Prefer using:

```javascript
console.log('>>', arg.request.method, arg.fullUri(), '>', arg.response.statusCode, arg.response.statusMessage);
```

I let you close the issue if you think it is solved.

Thank you for your contribution.

**Comment by lastuniverse** [comment] 2018-02-13 17:22
Thank you for your work.

Now everything is copied, transferred and deleted.
But ...
... for example, os Windows 7, the folder 622c is taken, it contains 5 files with a total weight of 1.44 megabytes. When you drag this folder to the root of the drive connected to the webdav, copying begins. It lasts about 15 minutes. In this case, the webdav server console displays:
```
>> PROPFIND http://192.168.0.10:1900/ > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/ > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/ > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/ > 207 Multi-Status
>> MKCOL http://192.168.0.10:1900/622c > 401 Unauthorized
>> MKCOL http://192.168.0.10:1900/622c > 201 Created
>> PROPPATCH http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/622C.IMG > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/ > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/ > 207 Multi-Status
>> PUT http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/622C.IMG > 201 Created
>> LOCK http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> LOCK http://192.168.0.10:1900/622c/622C.IMG > 200 OK
>> HEAD http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> HEAD http://192.168.0.10:1900/622c/622C.IMG > 200 OK
>> PUT http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/622C.IMG > 200 OK
>> PROPPATCH http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/622C.IMG > 207 Multi-Status
>> PROPPATCH http://192.168.0.10:1900/622c/622C.IMG > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/622C.IMG > 207 Multi-Status
>> UNLOCK http://192.168.0.10:1900/622c/622C.IMG > 409 Conflict
>> PROPFIND http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/FIRM.COM > 404 Not Found
>> PUT http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/FIRM.COM > 201 Created
>> LOCK http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> LOCK http://192.168.0.10:1900/622c/FIRM.COM > 200 OK
>> HEAD http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> HEAD http://192.168.0.10:1900/622c/FIRM.COM > 200 OK
>> PUT http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/FIRM.COM > 200 OK
>> PROPPATCH http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/FIRM.COM > 207 Multi-Status
>> PROPPATCH http://192.168.0.10:1900/622c/FIRM.COM > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/FIRM.COM > 207 Multi-Status
>> UNLOCK http://192.168.0.10:1900/622c/FIRM.COM > 409 Conflict
>> PROPFIND http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/LICENCE.TXT > 404 Not Found
>> PUT http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/LICENCE.TXT > 201 Created
>> LOCK http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> LOCK http://192.168.0.10:1900/622c/LICENCE.TXT > 200 OK
>> HEAD http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> HEAD http://192.168.0.10:1900/622c/LICENCE.TXT > 200 OK
>> PUT http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/LICENCE.TXT > 200 OK
>> PROPPATCH http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/LICENCE.TXT > 207 Multi-Status
>> PROPPATCH http://192.168.0.10:1900/622c/LICENCE.TXT > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/LICENCE.TXT > 207 Multi-Status
>> UNLOCK http://192.168.0.10:1900/622c/LICENCE.TXT > 409 Conflict
>> PROPFIND http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/README.TXT > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c > 207 Multi-Status
>> PUT http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/README.TXT > 201 Created
>> LOCK http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> LOCK http://192.168.0.10:1900/622c/README.TXT > 200 OK
>> HEAD http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> HEAD http://192.168.0.10:1900/622c/README.TXT > 200 OK
>> PUT http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> PUT http://192.168.0.10:1900/622c/README.TXT > 200 OK
>> PROPPATCH http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/README.TXT > 207 Multi-Status
>> PROPPATCH http://192.168.0.10:1900/622c/README.TXT > 401 Unauthorized
>> PROPPATCH http://192.168.0.10:1900/622c/README.TXT > 207 Multi-Status
>> UNLOCK http://192.168.0.10:1900/622c/README.TXT > 409 Conflict
>> PROPFIND http://192.168.0.10:1900/ > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/ > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c/desktop.ini > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/desktop.ini > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c/folder.jpg > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/folder.jpg > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/622c/folder.gif > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/folder.gif > 404 Not Found
>> PROPFIND http://192.168.0.10:1900/622c > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c > 207 Multi-Status
>> PROPFIND http://192.168.0.10:1900/622c/Thumbs.db > 401 Unauthorized
>> PROPFIND http://192.168.0.10:1900/622c/Thumbs.db > 404 Not Found
```
How can I speed up the server?

**Comment by lastuniverse** [comment] 2018-02-13 18:02
To be fair, I want to note that when connecting to a webdav server from linux, using the dolphin file manager, by typing webdav in the address bar: //192.168.0.10: 1900 /
copying to the server a folder of node-modules (12k + files, total size of more than 500 megabytes) occurs almost instantly.
But unfortunately, I need a flexible webdav server for 38 users of windows (most of which have windows XP and windows 7)

**Comment by AdrienCastex** [comment] 2018-02-21 12:24
Hello,

15 minutes for 1.44 MB doesn't look to be linked to the program itself.

In your logs, I see only 4 files copied :
* 622C.IMG
* FIRM.COM
* LICENCE.TXT
* README.TXT

Can you please add the current time to your logs to see where the server his having trouble.

> To be fair, I want to note that when connecting to a webdav server from linux, using the dolphin file manager, by typing in the address bar "webdav://192.168.0.10: 1900/"

Do you mean : using `npm-webdav-server` or another webdav server?

**Comment by Jakobud** [comment] 2018-04-17 20:57
Where are you getting this webdav server console from? I'm (attempting to) running webdav-server on OSX and I'm getting some 207 Multi Status errors. I'd like to see some sort of log of what the server is doing.

**Comment by AdrienCastex** [comment] 2018-04-21 14:34
@Jakobud You can add some logs using:
```javascript
server.afterRequest((arg, next) => {
    // Display the method, the URI, the returned status code and the returned message
    console.log('>>', arg.request.method, arg.uri, '>', arg.response.statusCode, arg.response.statusMessage);
    // If available, display the body of the response
    console.log(arg.responseBody);
    next();
});
```

**Comment by AdrienCastex** [comment] 2018-09-02 09:39
I am closing this issue, the time to find a reproducible protocol.

**Closed by AdrienCastex** 2018-09-02 09:39 UTC
